{% set name = "pycobertura" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycobertura-{{ version }}.tar.gz
  sha256: 2fd51ce267e59d082004ef049f2fefc4babce92cf6579b0dec03d0c65752b82f

build:
  entry_points:
    - pycobertura=pycobertura.cli:pycobertura
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools-git
    - pip
  run:
    - python >=3.6
    - click >=4.0
    - jinja2
    - lxml
    - tabulate

test:
  imports:
    - pycobertura
  commands:
    - pip check
    - pycobertura --help
  requires:
    - pip

about:
  home: https://github.com/aconrad/pycobertura
  summary: A Cobertura coverage parser that can diff reports and show coverage progress.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - synapticarbors
